/* tslint:disable */
/* eslint-disable */
/**
 * Pharmacy Prescription API
 * Pharmacy Prescription management system
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: xkabac@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

