/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface PharmacyPrescriptionList {
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLPharmacyPrescriptionListElement extends Components.PharmacyPrescriptionList, HTMLStencilElement {
    }
    var HTMLPharmacyPrescriptionListElement: {
        prototype: HTMLPharmacyPrescriptionListElement;
        new (): HTMLPharmacyPrescriptionListElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "pharmacy-prescription-list": HTMLPharmacyPrescriptionListElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface PharmacyPrescriptionList {
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "pharmacy-prescription-list": PharmacyPrescriptionList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "pharmacy-prescription-list": LocalJSX.PharmacyPrescriptionList & JSXBase.HTMLAttributes<HTMLPharmacyPrescriptionListElement>;
        }
    }
}
